### ISSUE TITLE
Sanitize text from query before searching

### ISSUE THREAD

**Issue by diegofigs** [jpadilla/telegram-gate#4]
Queries with accents don't return the same amount of results as without accents. Sanitizing query before searching would make it a bit more user-friendly for grammar warriors.

Outputs:
q="Lugaro"
<img width="1440" alt="Screen Shot 2019-07-14 at 12 30 50 PM" src="https://user-images.githubusercontent.com/12281609/61186477-e0688580-a633-11e9-9c8c-7dc82d3e9f8c.png">

q="Lúgaro"
<img width="1440" alt="Screen Shot 2019-07-14 at 12 30 24 PM" src="https://user-images.githubusercontent.com/12281609/61186486-eeb6a180-a633-11e9-970a-945374e433d8.png">

Possible fix:
Have used [unidecode](https://www.npmjs.com/package/unidecode) in the past to sanitize accents before performing query. Let me know if PR's are welcome.

**Comment by jpadilla** [comment]
@diegofigs pull requests always welcome 👍 

Let me know, if you need anything. I can try and get to it later too.

**Comment by diegofigs** [comment]
I'll give it a go tonight. 'npm i && npm run dev' for running locally?

**Comment by jpadilla** [comment]
@diegofigs yeah!

**Comment by jonahoffline** [comment]
@diegofigs I didn't see you were going to work on this Tonight. I hope you don't mind,  but #5 is ready.

cc: @jpadilla
